using System;

namespace bLua.Extension
{
public static class Binder
{
public static void Bind(LuaRegister reg)
{
reg.Add("System.Object", typeof(object), null, typeof(System_Object));
reg.Add("System.Type", typeof(System.Type), null, typeof(System_Type));
reg.Add("System.Array", typeof(System.Array), null, typeof(System_Array));
reg.Add("System.Random", typeof(System.Random), null, typeof(System_Random));
reg.Add("System.ArrayInt", typeof(int[]), typeof(bLua.ArrayEx<int>), typeof(System.Array), typeof(System_ArrayInt));
reg.Add("System.ArrayFloat", typeof(float[]), typeof(bLua.ArrayEx<float>), typeof(System.Array), typeof(System_ArrayFloat));
reg.Add("System.ArrayString", typeof(string[]), typeof(bLua.ArrayEx<string>), typeof(System.Array), typeof(System_ArrayString));
reg.Add("System.ArrayObject", typeof(object[]), typeof(bLua.ArrayEx<object>), typeof(System.Array), typeof(System_ArrayObject));
reg.Add("System.Collections.Generic.ListInt", typeof(System.Collections.Generic.List<int>), null, typeof(System_Collections_Generic_ListInt));
reg.Add("System.Collections.Generic.ListFloat", typeof(System.Collections.Generic.List<float>), null, typeof(System_Collections_Generic_ListFloat));
reg.Add("System.Collections.Generic.ListString", typeof(System.Collections.Generic.List<string>), null, typeof(System_Collections_Generic_ListString));
reg.Add("System.Collections.Generic.ListObject", typeof(System.Collections.Generic.List<object>), null, typeof(System_Collections_Generic_ListObject));
reg.Add("UnityEngine.Object", typeof(UnityEngine.Object), null, typeof(UnityEngine_Object));
reg.Add("UnityEngine.MonoBehaviour", typeof(UnityEngine.MonoBehaviour), typeof(UnityEngine.Behaviour), typeof(UnityEngine_MonoBehaviour));
reg.Add("UnityEngine.Behaviour", typeof(UnityEngine.Behaviour), typeof(UnityEngine.Component), typeof(UnityEngine_Behaviour));
reg.Add("UnityEngine.Component", typeof(UnityEngine.Component), typeof(UnityEngine.Object), typeof(UnityEngine_Component));
reg.Add("UnityEngine.GameObject", typeof(UnityEngine.GameObject), typeof(bLua.GameObjectEx), typeof(UnityEngine.Object), typeof(UnityEngine_GameObject));
reg.Add("UnityEngine.Debug", typeof(UnityEngine.Debug), null, typeof(UnityEngine_Debug));
reg.Add("UnityEngine.Input", typeof(UnityEngine.Input), null, typeof(UnityEngine_Input));
reg.Add("UnityEngine.Time", typeof(UnityEngine.Time), null, typeof(UnityEngine_Time));
reg.Add("UnityEngine.Graphics", typeof(UnityEngine.Graphics), null, typeof(UnityEngine_Graphics));
reg.Add("UnityEngine.Screen", typeof(UnityEngine.Screen), null, typeof(UnityEngine_Screen));
reg.Add("UnityEngine.Application", typeof(UnityEngine.Application), null, typeof(UnityEngine_Application));
reg.Add("UnityEngine.AssetBundle", typeof(UnityEngine.AssetBundle), typeof(UnityEngine.Object), typeof(UnityEngine_AssetBundle));
reg.Add("UnityEngine.Transform", typeof(UnityEngine.Transform), typeof(UnityEngine.Component), typeof(UnityEngine_Transform));
reg.Add("UnityEngine.Shader", typeof(UnityEngine.Shader), typeof(UnityEngine.Object), typeof(UnityEngine_Shader));
reg.Add("UnityEngine.Material", typeof(UnityEngine.Material), typeof(UnityEngine.Object), typeof(UnityEngine_Material));
reg.Add("UnityEngine.MaterialPropertyBlock", typeof(UnityEngine.MaterialPropertyBlock), null, typeof(UnityEngine_MaterialPropertyBlock));
reg.Add("UnityEngine.Renderer", typeof(UnityEngine.Renderer), typeof(UnityEngine.Component), typeof(UnityEngine_Renderer));
reg.Add("UnityEngine.MeshRenderer", typeof(UnityEngine.MeshRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_MeshRenderer));
reg.Add("UnityEngine.SkinnedMeshRenderer", typeof(UnityEngine.SkinnedMeshRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_SkinnedMeshRenderer));
reg.Add("UnityEngine.MeshFilter", typeof(UnityEngine.MeshFilter), typeof(UnityEngine.Component), typeof(UnityEngine_MeshFilter));
reg.Add("UnityEngine.Mesh", typeof(UnityEngine.Mesh), typeof(UnityEngine.Object), typeof(UnityEngine_Mesh));
reg.Add("UnityEngine.Texture", typeof(UnityEngine.Texture), typeof(UnityEngine.Object), typeof(UnityEngine_Texture));
reg.Add("UnityEngine.RenderTexture", typeof(UnityEngine.RenderTexture), typeof(UnityEngine.Texture), typeof(UnityEngine_RenderTexture));
reg.Add("UnityEngine.Texture2D", typeof(UnityEngine.Texture2D), typeof(UnityEngine.Texture), typeof(UnityEngine_Texture2D));
reg.Add("UnityEngine.Physics", typeof(UnityEngine.Physics), null, typeof(UnityEngine_Physics));
reg.Add("UnityEngine.Collider", typeof(UnityEngine.Collider), typeof(UnityEngine.Component), typeof(UnityEngine_Collider));
reg.Add("UnityEngine.MeshCollider", typeof(UnityEngine.MeshCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_MeshCollider));
reg.Add("UnityEngine.TrailRenderer", typeof(UnityEngine.TrailRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_TrailRenderer));
reg.Add("UnityEngine.LineRenderer", typeof(UnityEngine.LineRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_LineRenderer));
reg.Add("UnityEngine.BoxCollider", typeof(UnityEngine.BoxCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_BoxCollider));
reg.Add("UnityEngine.CapsuleCollider", typeof(UnityEngine.CapsuleCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_CapsuleCollider));
reg.Add("UnityEngine.SphereCollider", typeof(UnityEngine.SphereCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_SphereCollider));
reg.Add("UnityEngine.CharacterController", typeof(UnityEngine.CharacterController), typeof(UnityEngine.Collider), typeof(UnityEngine_CharacterController));
reg.Add("UnityEngine.Rigidbody", typeof(UnityEngine.Rigidbody), typeof(UnityEngine.Component), typeof(UnityEngine_Rigidbody));
reg.Add("UnityEngine.Animator", typeof(UnityEngine.Animator), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Animator));
reg.Add("UnityEngine.Animation", typeof(UnityEngine.Animation), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Animation));
reg.Add("UnityEngine.AnimationClip", typeof(UnityEngine.AnimationClip), typeof(UnityEngine.Motion), typeof(UnityEngine_AnimationClip));
reg.Add("UnityEngine.Motion", typeof(UnityEngine.Motion), typeof(UnityEngine.Object), typeof(UnityEngine_Motion));
reg.Add("UnityEngine.Light", typeof(UnityEngine.Light), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Light));
reg.Add("UnityEngine.Camera", typeof(UnityEngine.Camera), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Camera));
reg.Add("UnityEngine.ParticleSystem", typeof(UnityEngine.ParticleSystem), typeof(UnityEngine.Component), typeof(UnityEngine_ParticleSystem));
reg.Add("UnityEngine.Canvas", typeof(UnityEngine.Canvas), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Canvas));
reg.Add("UnityEngine.Mathf", typeof(UnityEngine.Mathf), null, typeof(UnityEngine_Mathf));
reg.Add("UnityEngine.Color", typeof(UnityEngine.Color), null, typeof(UnityEngine_Color));
reg.Add("UnityEngine.Quaternion", typeof(UnityEngine.Quaternion), null, typeof(UnityEngine_Quaternion));
reg.Add("UnityEngine.Vector4", typeof(UnityEngine.Vector4), null, typeof(UnityEngine_Vector4));
reg.Add("UnityEngine.Vector3", typeof(UnityEngine.Vector3), null, typeof(UnityEngine_Vector3));
reg.Add("UnityEngine.Vector2", typeof(UnityEngine.Vector2), null, typeof(UnityEngine_Vector2));
reg.Add("UnityEngine.Matrix4x4", typeof(UnityEngine.Matrix4x4), null, typeof(UnityEngine_Matrix4x4));
reg.Add("bLua.IUnityMethod", typeof(bLua.AutoWrap.IUnityMethod), null, typeof(bLua_IUnityMethod));
reg.Add("bLua.LogUtil", typeof(bLua.LogUtil), null, typeof(bLua_LogUtil));
reg.Add("bLua.Example", typeof(bLua.Example), typeof(UnityEngine.MonoBehaviour), typeof(bLua_Example));
reg.Add("bLua.Example02", typeof(bLua.Example02), typeof(UnityEngine.MonoBehaviour), typeof(bLua_Example02));
reg.Add("bLua.MoveSystem", typeof(bLua.MoveSystem), null, typeof(bLua_MoveSystem));
}
public static void TouchAll()
{
var L = IntPtr.Zero;
AutoWrap.PushMultRetNoGC(L, new bLua.AutoWrap.MultRet<bool, float>());
AutoWrap.PushMultRetNoGC(L, new bLua.AutoWrap.MultRet<bool, int>());
new AutoWrap.Action();
new AutoWrap.Action<bool, object, object, object>();
new AutoWrap.Action<bool, object, object>();
new AutoWrap.Action<bool, object>();
new AutoWrap.Action<bool>();
new AutoWrap.Action<float>();
new AutoWrap.Action<int, bool>();
new AutoWrap.Action<int, float>();
new AutoWrap.Action<int, int, bool, int>();
new AutoWrap.Action<int, int, bool>();
new AutoWrap.Action<int, int, int, int>();
new AutoWrap.Action<int, int, int>();
new AutoWrap.Action<int, int, object, object, object>();
new AutoWrap.Action<int, int>();
new AutoWrap.Action<int, object, bool>();
new AutoWrap.Action<int, object, int, int>();
new AutoWrap.Action<int, object, int>();
new AutoWrap.Action<int, object, object, int>();
new AutoWrap.Action<int, object>();
new AutoWrap.Action<int, UnityEngine.Color>();
new AutoWrap.Action<int, UnityEngine.Matrix4x4>();
new AutoWrap.Action<int, UnityEngine.Vector4>();
new AutoWrap.Action<int>();
new AutoWrap.Action<object, bool, bool>();
new AutoWrap.Action<object, bool, int>();
new AutoWrap.Action<object, bool>();
new AutoWrap.Action<object, float, bool, bool, bool>();
new AutoWrap.Action<object, float, bool, bool>();
new AutoWrap.Action<object, float, bool>();
new AutoWrap.Action<object, float, float, float, float, float>();
new AutoWrap.Action<object, float, float, float, float>();
new AutoWrap.Action<object, float, float, float, int>();
new AutoWrap.Action<object, float, float, float, object>();
new AutoWrap.Action<object, float, float, float>();
new AutoWrap.Action<object, float, float>();
new AutoWrap.Action<object, float, UnityEngine.Vector3, float, float, int>();
new AutoWrap.Action<object, float, UnityEngine.Vector3, float, float>();
new AutoWrap.Action<object, float, UnityEngine.Vector3, float>();
new AutoWrap.Action<object, float>();
new AutoWrap.Action<object, int, bool>();
new AutoWrap.Action<object, int, float, float, float>();
new AutoWrap.Action<object, int, float, int, float, float>();
new AutoWrap.Action<object, int, float, int, float>();
new AutoWrap.Action<object, int, float, int>();
new AutoWrap.Action<object, int, float>();
new AutoWrap.Action<object, int, int, float>();
new AutoWrap.Action<object, int, int, int, int, object, int>();
new AutoWrap.Action<object, int, int, int, int, object>();
new AutoWrap.Action<object, int, int, int>();
new AutoWrap.Action<object, int, int, object, int, int>();
new AutoWrap.Action<object, int, int, object, object, object>();
new AutoWrap.Action<object, int, int, object>();
new AutoWrap.Action<object, int, int, UnityEngine.Color, int>();
new AutoWrap.Action<object, int, int, UnityEngine.Color>();
new AutoWrap.Action<object, int, int>();
new AutoWrap.Action<object, int, object, int, int, int>();
new AutoWrap.Action<object, int, object, int, int>();
new AutoWrap.Action<object, int, object, int>();
new AutoWrap.Action<object, int, object, object, int, object, int, bool, int, object>();
new AutoWrap.Action<object, int, object, object, int, object, int, bool, int>();
new AutoWrap.Action<object, int, object, object, int, object, int, bool>();
new AutoWrap.Action<object, int, object, object, int, object, int>();
new AutoWrap.Action<object, int, object, object, int, object>();
new AutoWrap.Action<object, int, object, object, int>();
new AutoWrap.Action<object, int, object, object>();
new AutoWrap.Action<object, int, object>();
new AutoWrap.Action<object, int, UnityEngine.Color>();
new AutoWrap.Action<object, int, UnityEngine.Matrix4x4>();
new AutoWrap.Action<object, int, UnityEngine.Quaternion>();
new AutoWrap.Action<object, int, UnityEngine.Rendering.SubMeshDescriptor, int>();
new AutoWrap.Action<object, int, UnityEngine.Vector2>();
new AutoWrap.Action<object, int, UnityEngine.Vector3>();
new AutoWrap.Action<object, int, UnityEngine.Vector4>();
new AutoWrap.Action<object, int>();
new AutoWrap.Action<object, long, object, long, long>();
new AutoWrap.Action<object, object, bool, bool, bool>();
new AutoWrap.Action<object, object, bool, bool>();
new AutoWrap.Action<object, object, bool>();
new AutoWrap.Action<object, object, float, float, float>();
new AutoWrap.Action<object, object, float, float>();
new AutoWrap.Action<object, object, float, int, float, float>();
new AutoWrap.Action<object, object, float, int, float>();
new AutoWrap.Action<object, object, float, int>();
new AutoWrap.Action<object, object, float, object, object, object>();
new AutoWrap.Action<object, object, float>();
new AutoWrap.Action<object, object, int, bool, int>();
new AutoWrap.Action<object, object, int, bool>();
new AutoWrap.Action<object, object, int, float>();
new AutoWrap.Action<object, object, int, int, bool, int>();
new AutoWrap.Action<object, object, int, int, bool>();
new AutoWrap.Action<object, object, int, int, int, bool, int>();
new AutoWrap.Action<object, object, int, int, int, int, bool, int>();
new AutoWrap.Action<object, object, int, int, int>();
new AutoWrap.Action<object, object, int, int, object>();
new AutoWrap.Action<object, object, int, int>();
new AutoWrap.Action<object, object, int>();
new AutoWrap.Action<object, object, long, long, long>();
new AutoWrap.Action<object, object, long, long>();
new AutoWrap.Action<object, object, long>();
new AutoWrap.Action<object, object, object, bool>();
new AutoWrap.Action<object, object, object, float>();
new AutoWrap.Action<object, object, object, int, int, bool>();
new AutoWrap.Action<object, object, object, int, int>();
new AutoWrap.Action<object, object, object, int, object>();
new AutoWrap.Action<object, object, object, int>();
new AutoWrap.Action<object, object, object, object, object>();
new AutoWrap.Action<object, object, object, object>();
new AutoWrap.Action<object, object, object>();
new AutoWrap.Action<object, object, UnityEngine.Color>();
new AutoWrap.Action<object, object, UnityEngine.Matrix4x4>();
new AutoWrap.Action<object, object, UnityEngine.RenderBuffer>();
new AutoWrap.Action<object, object, UnityEngine.Vector2, UnityEngine.Vector2, int, int>();
new AutoWrap.Action<object, object, UnityEngine.Vector2, UnityEngine.Vector2>();
new AutoWrap.Action<object, object, UnityEngine.Vector2>();
new AutoWrap.Action<object, object, UnityEngine.Vector3>();
new AutoWrap.Action<object, object, UnityEngine.Vector4>();
new AutoWrap.Action<object, object>();
new AutoWrap.Action<object, System.IntPtr, int>();
new AutoWrap.Action<object, System.IntPtr>();
new AutoWrap.Action<object, uint>();
new AutoWrap.Action<object, ulong>();
new AutoWrap.Action<object, UnityEngine.Bounds, int, int, int, object, object, int, bool, int>();
new AutoWrap.Action<object, UnityEngine.Bounds, int, object, int, object, object, int, bool, int>();
new AutoWrap.Action<object, UnityEngine.Bounds>();
new AutoWrap.Action<object, UnityEngine.Color>();
new AutoWrap.Action<object, UnityEngine.LightBakingOutput>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, int>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, bool, bool, bool>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, bool, bool>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, bool>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, int, bool, object>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, int, bool>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object, int>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int, object>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object, int>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int, object>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4, object, int>();
new AutoWrap.Action<object, UnityEngine.Matrix4x4>();
new AutoWrap.Action<object, UnityEngine.ParticleSystem.EmitParams, int>();
new AutoWrap.Action<object, UnityEngine.ParticleSystem.PlaybackState>();
new AutoWrap.Action<object, UnityEngine.ParticleSystem.Trails>();
new AutoWrap.Action<object, UnityEngine.Quaternion>();
new AutoWrap.Action<object, UnityEngine.Rect, float, int, object>();
new AutoWrap.Action<object, UnityEngine.Rect, int, int, bool>();
new AutoWrap.Action<object, UnityEngine.Rect, int, int>();
new AutoWrap.Action<object, UnityEngine.Rect>();
new AutoWrap.Action<object, UnityEngine.RenderBuffer, UnityEngine.RenderBuffer>();
new AutoWrap.Action<object, UnityEngine.RenderBuffer>();
new AutoWrap.Action<object, UnityEngine.RenderTextureDescriptor>();
new AutoWrap.Action<object, UnityEngine.SceneManagement.Scene>();
new AutoWrap.Action<object, UnityEngine.Vector2>();
new AutoWrap.Action<object, UnityEngine.Vector3, float, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, float>();
new AutoWrap.Action<object, UnityEngine.Vector3, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, object>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float, float, bool>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float, float>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int, object, bool, bool>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int, object, bool>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int, object, int, bool>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int, object, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int, object>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int, object>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Vector3>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3, float>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3, int>();
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3>();
new AutoWrap.Action<object, UnityEngine.Vector3>();
new AutoWrap.Action<object, UnityEngine.Vector4>();
new AutoWrap.Action<object>();
new AutoWrap.Action<UnityEngine.Bounds, int>();
new AutoWrap.Action<UnityEngine.Mesh.MeshDataArray, object, int>();
new AutoWrap.Action<UnityEngine.Rect, object, int, int, int, int, object, int>();
new AutoWrap.Action<UnityEngine.Rect, object, int, int, int, int, object>();
new AutoWrap.Action<UnityEngine.Rect, object, int, int, int, int>();
new AutoWrap.Action<UnityEngine.Rect, object, object, int>();
new AutoWrap.Action<UnityEngine.Rect, object, object>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int, object, int>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int, object>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int, UnityEngine.Color, object, int>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int, UnityEngine.Color, object>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int, UnityEngine.Color>();
new AutoWrap.Action<UnityEngine.Rect, object, UnityEngine.Rect, int, int, int, int>();
new AutoWrap.Action<UnityEngine.Rect, object>();
new AutoWrap.Action<UnityEngine.RenderBuffer, UnityEngine.RenderBuffer, int, int, int>();
new AutoWrap.Action<UnityEngine.RenderBuffer, UnityEngine.RenderBuffer, int, int>();
new AutoWrap.Action<UnityEngine.RenderBuffer, UnityEngine.RenderBuffer, int>();
new AutoWrap.Action<UnityEngine.RenderBuffer, UnityEngine.RenderBuffer>();
new AutoWrap.Action<UnityEngine.Rendering.GraphicsFence, int>();
new AutoWrap.Action<UnityEngine.Rendering.GraphicsFence>();
new AutoWrap.Action<UnityEngine.RenderTargetSetup>();
new AutoWrap.Action<UnityEngine.Vector2>();
new AutoWrap.Action<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Color, float, bool>();
new AutoWrap.Action<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Color, float>();
new AutoWrap.Action<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Color>();
new AutoWrap.Action<UnityEngine.Vector3, UnityEngine.Vector3>();
new AutoWrap.Action<UnityEngine.Vector3>();
new AutoWrap.Func<bool>();
new AutoWrap.Func<double>();
new AutoWrap.Func<float, float, bool>();
new AutoWrap.Func<float, float, float, bool, UnityEngine.Color>();
new AutoWrap.Func<float, float, float, float, float, float, UnityEngine.Matrix4x4>();
new AutoWrap.Func<float, float, float, float, UnityEngine.Matrix4x4>();
new AutoWrap.Func<float, float, float, float>();
new AutoWrap.Func<float, float, float, UnityEngine.Color>();
new AutoWrap.Func<float, float, float, UnityEngine.Quaternion>();
new AutoWrap.Func<float, float, float>();
new AutoWrap.Func<float, float>();
new AutoWrap.Func<float, int>();
new AutoWrap.Func<float, UnityEngine.Color>();
new AutoWrap.Func<float, UnityEngine.Vector3, UnityEngine.Quaternion>();
new AutoWrap.Func<float, ushort>();
new AutoWrap.Func<float>();
new AutoWrap.Func<int, bool>();
new AutoWrap.Func<int, float>();
new AutoWrap.Func<int, int, bool>();
new AutoWrap.Func<int, int, int, bool, bool, System.IntPtr, object>();
new AutoWrap.Func<int, int, int, int, int, int, int, bool, object>();
new AutoWrap.Func<int, int, int, int, int, int, int, int, bool, object>();
new AutoWrap.Func<int, int, int, int, int, int, int, int, object>();
new AutoWrap.Func<int, int, int, int, int, int, int, object>();
new AutoWrap.Func<int, int, int, int, int, int, object>();
new AutoWrap.Func<int, int, int, int, int, object>();
new AutoWrap.Func<int, int, int, int, object>();
new AutoWrap.Func<int, int, int, int>();
new AutoWrap.Func<int, int, int, object>();
new AutoWrap.Func<int, int, int>();
new AutoWrap.Func<int, int, object>();
new AutoWrap.Func<int, int, UnityEngine.Rendering.GraphicsFence>();
new AutoWrap.Func<int, int>();
new AutoWrap.Func<int, object>();
new AutoWrap.Func<int, UnityEngine.AccelerationEvent>();
new AutoWrap.Func<int, UnityEngine.Color>();
new AutoWrap.Func<int, UnityEngine.Matrix4x4>();
new AutoWrap.Func<int, UnityEngine.Mesh.MeshDataArray>();
new AutoWrap.Func<int, UnityEngine.Rendering.GraphicsFence>();
new AutoWrap.Func<int, UnityEngine.Touch>();
new AutoWrap.Func<int, UnityEngine.Vector4>();
new AutoWrap.Func<int>();
new AutoWrap.Func<object, bLua.AutoWrap.MultRet<bool, int>>();
new AutoWrap.Func<object, bool, bool>();
new AutoWrap.Func<object, bool, object>();
new AutoWrap.Func<object, bool>();
new AutoWrap.Func<object, double>();
new AutoWrap.Func<object, float, bool>();
new AutoWrap.Func<object, float, float, float, UnityEngine.Vector3>();
new AutoWrap.Func<object, float, float, int, UnityEngine.Color>();
new AutoWrap.Func<object, float, float, UnityEngine.Color>();
new AutoWrap.Func<object, float, int, int, int>();
new AutoWrap.Func<object, float, int, int>();
new AutoWrap.Func<object, float, int>();
new AutoWrap.Func<object, float>();
new AutoWrap.Func<object, int, bool, object>();
new AutoWrap.Func<object, int, bool>();
new AutoWrap.Func<object, int, float>();
new AutoWrap.Func<object, int, int, bool>();
new AutoWrap.Func<object, int, int, float>();
new AutoWrap.Func<object, int, int, int, int, int, object>();
new AutoWrap.Func<object, int, int, int, int, object>();
new AutoWrap.Func<object, int, int, int, int>();
new AutoWrap.Func<object, int, int, int, object>();
new AutoWrap.Func<object, int, int, int, UnityEngine.Color>();
new AutoWrap.Func<object, int, int, int>();
new AutoWrap.Func<object, int, int, object, int>();
new AutoWrap.Func<object, int, int, object, object, int>();
new AutoWrap.Func<object, int, int, object>();
new AutoWrap.Func<object, int, int, UnityEngine.Color>();
new AutoWrap.Func<object, int, int>();
new AutoWrap.Func<object, int, long>();
new AutoWrap.Func<object, int, object, float, int, int, int, int, bLua.AutoWrap.MultRet<bool, float>>();
new AutoWrap.Func<object, int, object, int, bool>();
new AutoWrap.Func<object, int, object, int>();
new AutoWrap.Func<object, int, object>();
new AutoWrap.Func<object, int, System.IntPtr>();
new AutoWrap.Func<object, int, uint>();
new AutoWrap.Func<object, int, UnityEngine.AnimatorStateInfo>();
new AutoWrap.Func<object, int, UnityEngine.AnimatorTransitionInfo>();
new AutoWrap.Func<object, int, UnityEngine.Color>();
new AutoWrap.Func<object, int, UnityEngine.Matrix4x4>();
new AutoWrap.Func<object, int, UnityEngine.Quaternion>();
new AutoWrap.Func<object, int, UnityEngine.Rendering.ShaderTagId, UnityEngine.Rendering.ShaderTagId>();
new AutoWrap.Func<object, int, UnityEngine.Rendering.SubMeshDescriptor>();
new AutoWrap.Func<object, int, UnityEngine.Rendering.VertexAttributeDescriptor>();
new AutoWrap.Func<object, int, UnityEngine.Vector2>();
new AutoWrap.Func<object, int, UnityEngine.Vector3>();
new AutoWrap.Func<object, int, UnityEngine.Vector4>();
new AutoWrap.Func<object, int>();
new AutoWrap.Func<object, long, long, long, object>();
new AutoWrap.Func<object, long, long, object>();
new AutoWrap.Func<object, long, object>();
new AutoWrap.Func<object, long>();
new AutoWrap.Func<object, object, bool, object, object>();
new AutoWrap.Func<object, object, bool, object>();
new AutoWrap.Func<object, object, bool>();
new AutoWrap.Func<object, object, float, int, int, object>();
new AutoWrap.Func<object, object, float, int, object>();
new AutoWrap.Func<object, object, float, object>();
new AutoWrap.Func<object, object, float>();
new AutoWrap.Func<object, object, int, bool>();
new AutoWrap.Func<object, object, int, int, bool, object>();
new AutoWrap.Func<object, object, int, int, bool>();
new AutoWrap.Func<object, object, int, int, int>();
new AutoWrap.Func<object, object, int, int, object>();
new AutoWrap.Func<object, object, int, int>();
new AutoWrap.Func<object, object, int, object>();
new AutoWrap.Func<object, object, int>();
new AutoWrap.Func<object, object, object, int>();
new AutoWrap.Func<object, object, object, object>();
new AutoWrap.Func<object, object, object>();
new AutoWrap.Func<object, object, UnityEngine.BuildCompression, uint, int, object>();
new AutoWrap.Func<object, object, UnityEngine.Color>();
new AutoWrap.Func<object, object, UnityEngine.Matrix4x4>();
new AutoWrap.Func<object, object, UnityEngine.Vector2>();
new AutoWrap.Func<object, object, UnityEngine.Vector4>();
new AutoWrap.Func<object, object>();
new AutoWrap.Func<object, System.IntPtr>();
new AutoWrap.Func<object, uint, object>();
new AutoWrap.Func<object, uint, uint, object>();
new AutoWrap.Func<object, uint, ulong, object>();
new AutoWrap.Func<object, uint>();
new AutoWrap.Func<object, ulong>();
new AutoWrap.Func<object, Unity.Collections.NativeArray<System.Byte>>();
new AutoWrap.Func<object, Unity.Collections.NativeArray<UnityEngine.BoneWeight1>>();
new AutoWrap.Func<object, UnityEngine.Bounds>();
new AutoWrap.Func<object, UnityEngine.Color, bool>();
new AutoWrap.Func<object, UnityEngine.Color>();
new AutoWrap.Func<object, UnityEngine.FrustumPlanes>();
new AutoWrap.Func<object, UnityEngine.LightBakingOutput>();
new AutoWrap.Func<object, UnityEngine.Matrix4x4, bool>();
new AutoWrap.Func<object, UnityEngine.Matrix4x4>();
new AutoWrap.Func<object, UnityEngine.Mesh.MeshDataArray>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.CollisionModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ColorBySpeedModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ColorOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.CustomDataModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.EmissionModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ExternalForcesModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ForceOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.InheritVelocityModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LifetimeByEmitterSpeedModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LightsModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LimitVelocityOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.MainModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.NoiseModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.PlaybackState>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.RotationBySpeedModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.RotationOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ShapeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SizeBySpeedModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SizeOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SubEmittersModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TextureSheetAnimationModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TrailModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.Trails>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TriggerModule>();
new AutoWrap.Func<object, UnityEngine.ParticleSystem.VelocityOverLifetimeModule>();
new AutoWrap.Func<object, UnityEngine.Plane, UnityEngine.Plane>();
new AutoWrap.Func<object, UnityEngine.Playables.PlayableGraph>();
new AutoWrap.Func<object, UnityEngine.Quaternion, bool>();
new AutoWrap.Func<object, UnityEngine.Quaternion>();
new AutoWrap.Func<object, UnityEngine.Rect>();
new AutoWrap.Func<object, UnityEngine.RenderBuffer>();
new AutoWrap.Func<object, UnityEngine.RenderTextureDescriptor>();
new AutoWrap.Func<object, UnityEngine.SceneManagement.Scene>();
new AutoWrap.Func<object, UnityEngine.Vector2, bool>();
new AutoWrap.Func<object, UnityEngine.Vector2>();
new AutoWrap.Func<object, UnityEngine.Vector3, bool>();
new AutoWrap.Func<object, UnityEngine.Vector3, float, int, object>();
new AutoWrap.Func<object, UnityEngine.Vector3, float, object>();
new AutoWrap.Func<object, UnityEngine.Vector3, int, UnityEngine.Ray>();
new AutoWrap.Func<object, UnityEngine.Vector3, int, UnityEngine.Vector3>();
new AutoWrap.Func<object, UnityEngine.Vector3, int>();
new AutoWrap.Func<object, UnityEngine.Vector3, object>();
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Quaternion, object, object>();
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Quaternion, object>();
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Ray>();
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Vector3>();
new AutoWrap.Func<object, UnityEngine.Vector3>();
new AutoWrap.Func<object, UnityEngine.Vector4, bool>();
new AutoWrap.Func<object, UnityEngine.Vector4, UnityEngine.Matrix4x4>();
new AutoWrap.Func<object, UnityEngine.Vector4>();
new AutoWrap.Func<object>();
new AutoWrap.Func<ulong>();
new AutoWrap.Func<UnityEngine.Color, UnityEngine.Color, float, UnityEngine.Color>();
new AutoWrap.Func<UnityEngine.Color>();
new AutoWrap.Func<UnityEngine.FrustumPlanes, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Matrix4x4, float>();
new AutoWrap.Func<UnityEngine.Matrix4x4, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.PhysicsScene>();
new AutoWrap.Func<UnityEngine.Quaternion, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Quaternion, UnityEngine.Quaternion, float, UnityEngine.Quaternion>();
new AutoWrap.Func<UnityEngine.Quaternion, UnityEngine.Quaternion, float>();
new AutoWrap.Func<UnityEngine.Quaternion, UnityEngine.Quaternion>();
new AutoWrap.Func<UnityEngine.Quaternion>();
new AutoWrap.Func<UnityEngine.Ray, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, float, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, float, int, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Ray, float, float, int, object>();
new AutoWrap.Func<UnityEngine.Ray, float, float, object>();
new AutoWrap.Func<UnityEngine.Ray, float, int, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Ray, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Ray, float, int, object>();
new AutoWrap.Func<UnityEngine.Ray, float, object, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Ray, float, object, float, int, int>();
new AutoWrap.Func<UnityEngine.Ray, float, object, float, int>();
new AutoWrap.Func<UnityEngine.Ray, float, object, int>();
new AutoWrap.Func<UnityEngine.Ray, float, object>();
new AutoWrap.Func<UnityEngine.Ray, object, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Ray, object, float, int, int>();
new AutoWrap.Func<UnityEngine.Ray, object, float, int>();
new AutoWrap.Func<UnityEngine.Ray, object, int>();
new AutoWrap.Func<UnityEngine.Ray, object>();
new AutoWrap.Func<UnityEngine.Rect>();
new AutoWrap.Func<UnityEngine.RenderBuffer>();
new AutoWrap.Func<UnityEngine.Rendering.GraphicsFence>();
new AutoWrap.Func<UnityEngine.RenderTextureDescriptor, object>();
new AutoWrap.Func<UnityEngine.Resolution>();
new AutoWrap.Func<UnityEngine.Vector2, float, UnityEngine.Vector2>();
new AutoWrap.Func<UnityEngine.Vector2, float>();
new AutoWrap.Func<UnityEngine.Vector2, UnityEngine.Vector2, float, UnityEngine.Vector2>();
new AutoWrap.Func<UnityEngine.Vector2, UnityEngine.Vector2, float>();
new AutoWrap.Func<UnityEngine.Vector2, UnityEngine.Vector2, UnityEngine.Vector2>();
new AutoWrap.Func<UnityEngine.Vector2, UnityEngine.Vector2>();
new AutoWrap.Func<UnityEngine.Vector2>();
new AutoWrap.Func<UnityEngine.Vector3, float, bool>();
new AutoWrap.Func<UnityEngine.Vector3, float, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, object, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, object, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, float, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3, object>();
new AutoWrap.Func<UnityEngine.Vector3, float, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3, float>();
new AutoWrap.Func<UnityEngine.Vector3, object, UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Vector3, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Quaternion>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, float, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, object, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, object, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, float, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, object, float, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, float>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, float, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, float, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, float>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, float, int, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, float, int, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, float, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object, UnityEngine.Quaternion, int>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Matrix4x4>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, int, int, bool>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, int, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, int, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, float, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Quaternion, object>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3, UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector3>();
new AutoWrap.Func<UnityEngine.Vector4, float>();
new AutoWrap.Func<UnityEngine.Vector4, UnityEngine.Vector4, float, UnityEngine.Vector4>();
new AutoWrap.Func<UnityEngine.Vector4, UnityEngine.Vector4, float>();
new AutoWrap.Func<UnityEngine.Vector4, UnityEngine.Vector4, UnityEngine.Vector4>();
new AutoWrap.Func<UnityEngine.Vector4, UnityEngine.Vector4>();
new AutoWrap.Func<UnityEngine.Vector4>();
new AutoWrap.Func<ushort, float>();
}
}
}
