using System;

namespace bLua.Extension
{
public static class Binder
{
public static void Bind(LuaRegister reg)
{
reg.Add("System.Object", typeof(object), null, typeof(System_Object));
reg.Add("System.Type", typeof(System.Type), null, typeof(System_Type));
reg.Add("System.Array", typeof(System.Array), null, typeof(System_Array));
reg.Add("System.Random", typeof(System.Random), null, typeof(System_Random));
reg.Add("System.ArrayInt", typeof(int[]), typeof(bLua.ArrayEx<int>), typeof(System.Array), typeof(System_ArrayInt));
reg.Add("System.ArrayFloat", typeof(float[]), typeof(bLua.ArrayEx<float>), typeof(System.Array), typeof(System_ArrayFloat));
reg.Add("System.ArrayString", typeof(string[]), typeof(bLua.ArrayEx<string>), typeof(System.Array), typeof(System_ArrayString));
reg.Add("System.ArrayObject", typeof(object[]), typeof(bLua.ArrayEx<object>), typeof(System.Array), typeof(System_ArrayObject));
reg.Add("System.Collections.Generic.ListInt", typeof(System.Collections.Generic.List<int>), null, typeof(System_Collections_Generic_ListInt));
reg.Add("System.Collections.Generic.ListFloat", typeof(System.Collections.Generic.List<float>), null, typeof(System_Collections_Generic_ListFloat));
reg.Add("System.Collections.Generic.ListString", typeof(System.Collections.Generic.List<string>), null, typeof(System_Collections_Generic_ListString));
reg.Add("System.Collections.Generic.ListObject", typeof(System.Collections.Generic.List<object>), null, typeof(System_Collections_Generic_ListObject));
reg.Add("UnityEngine.Object", typeof(UnityEngine.Object), null, typeof(UnityEngine_Object));
reg.Add("UnityEngine.MonoBehaviour", typeof(UnityEngine.MonoBehaviour), typeof(UnityEngine.Behaviour), typeof(UnityEngine_MonoBehaviour));
reg.Add("UnityEngine.Behaviour", typeof(UnityEngine.Behaviour), typeof(UnityEngine.Component), typeof(UnityEngine_Behaviour));
reg.Add("UnityEngine.Component", typeof(UnityEngine.Component), typeof(UnityEngine.Object), typeof(UnityEngine_Component));
reg.Add("UnityEngine.GameObject", typeof(UnityEngine.GameObject), typeof(bLua.GameObjectEx), typeof(UnityEngine.Object), typeof(UnityEngine_GameObject));
reg.Add("UnityEngine.Debug", typeof(UnityEngine.Debug), null, typeof(UnityEngine_Debug));
reg.Add("UnityEngine.Input", typeof(UnityEngine.Input), null, typeof(UnityEngine_Input));
reg.Add("UnityEngine.Time", typeof(UnityEngine.Time), null, typeof(UnityEngine_Time));
reg.Add("UnityEngine.Graphics", typeof(UnityEngine.Graphics), null, typeof(UnityEngine_Graphics));
reg.Add("UnityEngine.Screen", typeof(UnityEngine.Screen), null, typeof(UnityEngine_Screen));
reg.Add("UnityEngine.Application", typeof(UnityEngine.Application), null, typeof(UnityEngine_Application));
reg.Add("UnityEngine.AssetBundle", typeof(UnityEngine.AssetBundle), typeof(UnityEngine.Object), typeof(UnityEngine_AssetBundle));
reg.Add("UnityEngine.Transform", typeof(UnityEngine.Transform), typeof(UnityEngine.Component), typeof(UnityEngine_Transform));
reg.Add("UnityEngine.Shader", typeof(UnityEngine.Shader), typeof(UnityEngine.Object), typeof(UnityEngine_Shader));
reg.Add("UnityEngine.Material", typeof(UnityEngine.Material), typeof(UnityEngine.Object), typeof(UnityEngine_Material));
reg.Add("UnityEngine.MaterialPropertyBlock", typeof(UnityEngine.MaterialPropertyBlock), null, typeof(UnityEngine_MaterialPropertyBlock));
reg.Add("UnityEngine.Renderer", typeof(UnityEngine.Renderer), typeof(UnityEngine.Component), typeof(UnityEngine_Renderer));
reg.Add("UnityEngine.MeshRenderer", typeof(UnityEngine.MeshRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_MeshRenderer));
reg.Add("UnityEngine.SkinnedMeshRenderer", typeof(UnityEngine.SkinnedMeshRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_SkinnedMeshRenderer));
reg.Add("UnityEngine.MeshFilter", typeof(UnityEngine.MeshFilter), typeof(UnityEngine.Component), typeof(UnityEngine_MeshFilter));
reg.Add("UnityEngine.Mesh", typeof(UnityEngine.Mesh), typeof(UnityEngine.Object), typeof(UnityEngine_Mesh));
reg.Add("UnityEngine.Texture", typeof(UnityEngine.Texture), typeof(UnityEngine.Object), typeof(UnityEngine_Texture));
reg.Add("UnityEngine.RenderTexture", typeof(UnityEngine.RenderTexture), typeof(UnityEngine.Texture), typeof(UnityEngine_RenderTexture));
reg.Add("UnityEngine.Texture2D", typeof(UnityEngine.Texture2D), typeof(UnityEngine.Texture), typeof(UnityEngine_Texture2D));
reg.Add("UnityEngine.Physics", typeof(UnityEngine.Physics), null, typeof(UnityEngine_Physics));
reg.Add("UnityEngine.Collider", typeof(UnityEngine.Collider), typeof(UnityEngine.Component), typeof(UnityEngine_Collider));
reg.Add("UnityEngine.MeshCollider", typeof(UnityEngine.MeshCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_MeshCollider));
reg.Add("UnityEngine.TrailRenderer", typeof(UnityEngine.TrailRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_TrailRenderer));
reg.Add("UnityEngine.LineRenderer", typeof(UnityEngine.LineRenderer), typeof(UnityEngine.Renderer), typeof(UnityEngine_LineRenderer));
reg.Add("UnityEngine.BoxCollider", typeof(UnityEngine.BoxCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_BoxCollider));
reg.Add("UnityEngine.CapsuleCollider", typeof(UnityEngine.CapsuleCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_CapsuleCollider));
reg.Add("UnityEngine.SphereCollider", typeof(UnityEngine.SphereCollider), typeof(UnityEngine.Collider), typeof(UnityEngine_SphereCollider));
reg.Add("UnityEngine.CharacterController", typeof(UnityEngine.CharacterController), typeof(UnityEngine.Collider), typeof(UnityEngine_CharacterController));
reg.Add("UnityEngine.Rigidbody", typeof(UnityEngine.Rigidbody), typeof(UnityEngine.Component), typeof(UnityEngine_Rigidbody));
reg.Add("UnityEngine.Animator", typeof(UnityEngine.Animator), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Animator));
reg.Add("UnityEngine.Animation", typeof(UnityEngine.Animation), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Animation));
reg.Add("UnityEngine.AnimationClip", typeof(UnityEngine.AnimationClip), typeof(UnityEngine.Motion), typeof(UnityEngine_AnimationClip));
reg.Add("UnityEngine.Motion", typeof(UnityEngine.Motion), typeof(UnityEngine.Object), typeof(UnityEngine_Motion));
reg.Add("UnityEngine.Light", typeof(UnityEngine.Light), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Light));
reg.Add("UnityEngine.Camera", typeof(UnityEngine.Camera), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Camera));
reg.Add("UnityEngine.ParticleSystem", typeof(UnityEngine.ParticleSystem), typeof(UnityEngine.Component), typeof(UnityEngine_ParticleSystem));
reg.Add("UnityEngine.Canvas", typeof(UnityEngine.Canvas), typeof(UnityEngine.Behaviour), typeof(UnityEngine_Canvas));
reg.Add("UnityEngine.Mathf", typeof(UnityEngine.Mathf), null, typeof(UnityEngine_Mathf));
reg.Add("UnityEngine.Color", typeof(UnityEngine.Color), null, typeof(UnityEngine_Color));
reg.Add("UnityEngine.Quaternion", typeof(UnityEngine.Quaternion), null, typeof(UnityEngine_Quaternion));
reg.Add("UnityEngine.Vector4", typeof(UnityEngine.Vector4), null, typeof(UnityEngine_Vector4));
reg.Add("UnityEngine.Vector3", typeof(UnityEngine.Vector3), null, typeof(UnityEngine_Vector3));
reg.Add("UnityEngine.Vector2", typeof(UnityEngine.Vector2), null, typeof(UnityEngine_Vector2));
reg.Add("UnityEngine.Matrix4x4", typeof(UnityEngine.Matrix4x4), null, typeof(UnityEngine_Matrix4x4));
reg.Add("bLua.LuaDelegate", typeof(bLua.LuaDelegate), null, typeof(bLua_LuaDelegate));
reg.Add("bLua.LogUtil", typeof(bLua.LogUtil), null, typeof(bLua_LogUtil));
reg.Add("bLua.Example", typeof(bLua.Example), typeof(UnityEngine.MonoBehaviour), typeof(bLua_Example));
reg.Add("bLua.Example02", typeof(bLua.Example02), typeof(UnityEngine.MonoBehaviour), typeof(bLua_Example02));
reg.Add("bLua.MoveSystem", typeof(bLua.MoveSystem), null, typeof(bLua_MoveSystem));
}
public static void ListFuncType()
{
var L = IntPtr.Zero;
AutoWrap.PushMultRetNoGC(L, new bLua.AutoWrap.MultRet<bool, float>());
AutoWrap.PushMultRetNoGC(L, new bLua.AutoWrap.MultRet<bool, int>());
new AutoWrap.Action().Call(L);
new AutoWrap.Action<bool>().Call(L);
new AutoWrap.Action<float>().Call(L);
new AutoWrap.Action<int>().Call(L);
new AutoWrap.Action<object, bool, bool>().Call(L);
new AutoWrap.Action<object, bool, int>().Call(L);
new AutoWrap.Action<object, bool>().Call(L);
new AutoWrap.Action<object, float, bool, bool, bool>().Call(L);
new AutoWrap.Action<object, float, bool, bool>().Call(L);
new AutoWrap.Action<object, float, bool>().Call(L);
new AutoWrap.Action<object, float, float, float, float, float>().Call(L);
new AutoWrap.Action<object, float, float, float, float>().Call(L);
new AutoWrap.Action<object, float, float, float, int>().Call(L);
new AutoWrap.Action<object, float, float, float, object>().Call(L);
new AutoWrap.Action<object, float, float, float>().Call(L);
new AutoWrap.Action<object, float, float>().Call(L);
new AutoWrap.Action<object, float, UnityEngine.Vector3, float, float, int>().Call(L);
new AutoWrap.Action<object, float, UnityEngine.Vector3, float, float>().Call(L);
new AutoWrap.Action<object, float, UnityEngine.Vector3, float>().Call(L);
new AutoWrap.Action<object, float>().Call(L);
new AutoWrap.Action<object, int, bool>().Call(L);
new AutoWrap.Action<object, int, float, float, float>().Call(L);
new AutoWrap.Action<object, int, float, int, float, float>().Call(L);
new AutoWrap.Action<object, int, float, int, float>().Call(L);
new AutoWrap.Action<object, int, float, int>().Call(L);
new AutoWrap.Action<object, int, float>().Call(L);
new AutoWrap.Action<object, int, int, float>().Call(L);
new AutoWrap.Action<object, int, int, int, int, object, int>().Call(L);
new AutoWrap.Action<object, int, int, int, int, object>().Call(L);
new AutoWrap.Action<object, int, int, object, object, object>().Call(L);
new AutoWrap.Action<object, int, int, UnityEngine.Color, int>().Call(L);
new AutoWrap.Action<object, int, int, UnityEngine.Color>().Call(L);
new AutoWrap.Action<object, int, int>().Call(L);
new AutoWrap.Action<object, int, object, int, int, int>().Call(L);
new AutoWrap.Action<object, int, object, int, int>().Call(L);
new AutoWrap.Action<object, int, object, int>().Call(L);
new AutoWrap.Action<object, int, object>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Color>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Quaternion>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Rendering.SubMeshDescriptor, int>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Vector2>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Vector3>().Call(L);
new AutoWrap.Action<object, int, UnityEngine.Vector4>().Call(L);
new AutoWrap.Action<object, int>().Call(L);
new AutoWrap.Action<object, object, bool, bool, bool>().Call(L);
new AutoWrap.Action<object, object, bool, bool>().Call(L);
new AutoWrap.Action<object, object, bool>().Call(L);
new AutoWrap.Action<object, object, float, float, float>().Call(L);
new AutoWrap.Action<object, object, float, float>().Call(L);
new AutoWrap.Action<object, object, float, int, float, float>().Call(L);
new AutoWrap.Action<object, object, float, int, float>().Call(L);
new AutoWrap.Action<object, object, float, int>().Call(L);
new AutoWrap.Action<object, object, float, object, object, object>().Call(L);
new AutoWrap.Action<object, object, float>().Call(L);
new AutoWrap.Action<object, object, int, bool, int>().Call(L);
new AutoWrap.Action<object, object, int, bool>().Call(L);
new AutoWrap.Action<object, object, int, float>().Call(L);
new AutoWrap.Action<object, object, int, int, bool, int>().Call(L);
new AutoWrap.Action<object, object, int, int, bool>().Call(L);
new AutoWrap.Action<object, object, int, int, int, bool, int>().Call(L);
new AutoWrap.Action<object, object, int, int, int, int, bool, int>().Call(L);
new AutoWrap.Action<object, object, int, int, int>().Call(L);
new AutoWrap.Action<object, object, int, int>().Call(L);
new AutoWrap.Action<object, object, int>().Call(L);
new AutoWrap.Action<object, object, long, long, long>().Call(L);
new AutoWrap.Action<object, object, long, long>().Call(L);
new AutoWrap.Action<object, object, long>().Call(L);
new AutoWrap.Action<object, object, object, bool>().Call(L);
new AutoWrap.Action<object, object, object, float>().Call(L);
new AutoWrap.Action<object, object, object, int, int, bool>().Call(L);
new AutoWrap.Action<object, object, object, int, int>().Call(L);
new AutoWrap.Action<object, object, object, int>().Call(L);
new AutoWrap.Action<object, object, object, object, object>().Call(L);
new AutoWrap.Action<object, object, object>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.Color>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.RenderBuffer>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.Vector2>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.Vector3>().Call(L);
new AutoWrap.Action<object, object, UnityEngine.Vector4>().Call(L);
new AutoWrap.Action<object, object>().Call(L);
new AutoWrap.Action<object, System.IntPtr, int>().Call(L);
new AutoWrap.Action<object, System.IntPtr>().Call(L);
new AutoWrap.Action<object, uint>().Call(L);
new AutoWrap.Action<object, ulong>().Call(L);
new AutoWrap.Action<object, UnityEngine.Bounds>().Call(L);
new AutoWrap.Action<object, UnityEngine.Color>().Call(L);
new AutoWrap.Action<object, UnityEngine.LightBakingOutput>().Call(L);
new AutoWrap.Action<object, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Action<object, UnityEngine.ParticleSystem.EmitParams, int>().Call(L);
new AutoWrap.Action<object, UnityEngine.ParticleSystem.PlaybackState>().Call(L);
new AutoWrap.Action<object, UnityEngine.ParticleSystem.Trails>().Call(L);
new AutoWrap.Action<object, UnityEngine.Quaternion>().Call(L);
new AutoWrap.Action<object, UnityEngine.Rect, float, int, object>().Call(L);
new AutoWrap.Action<object, UnityEngine.Rect, int, int, bool>().Call(L);
new AutoWrap.Action<object, UnityEngine.Rect, int, int>().Call(L);
new AutoWrap.Action<object, UnityEngine.Rect>().Call(L);
new AutoWrap.Action<object, UnityEngine.RenderBuffer, UnityEngine.RenderBuffer>().Call(L);
new AutoWrap.Action<object, UnityEngine.RenderTextureDescriptor>().Call(L);
new AutoWrap.Action<object, UnityEngine.SceneManagement.Scene>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector2>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, float, int>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, float>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, int>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, object>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float, float, bool>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float, float>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, int, UnityEngine.MatchTargetWeightMask, float>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion, UnityEngine.Vector3>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Quaternion>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3, float>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3, int>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3, UnityEngine.Vector3>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector3>().Call(L);
new AutoWrap.Action<object, UnityEngine.Vector4>().Call(L);
new AutoWrap.Action<object>().Call(L);
new AutoWrap.Action<UnityEngine.Vector2>().Call(L);
new AutoWrap.Action<UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<bool>().Call(L);
new AutoWrap.Func<double>().Call(L);
new AutoWrap.Func<float>().Call(L);
new AutoWrap.Func<int>().Call(L);
new AutoWrap.Func<object, bLua.AutoWrap.MultRet<bool, int>>().Call(L);
new AutoWrap.Func<object, bool, bool>().Call(L);
new AutoWrap.Func<object, bool>().Call(L);
new AutoWrap.Func<object, double>().Call(L);
new AutoWrap.Func<object, float, bool>().Call(L);
new AutoWrap.Func<object, float, float, float, UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<object, float, float, int, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, float, float, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, float, int, int, int>().Call(L);
new AutoWrap.Func<object, float, int, int>().Call(L);
new AutoWrap.Func<object, float, int>().Call(L);
new AutoWrap.Func<object, float>().Call(L);
new AutoWrap.Func<object, int, bool, object>().Call(L);
new AutoWrap.Func<object, int, bool>().Call(L);
new AutoWrap.Func<object, int, float>().Call(L);
new AutoWrap.Func<object, int, int, bool>().Call(L);
new AutoWrap.Func<object, int, int, float>().Call(L);
new AutoWrap.Func<object, int, int, int, int, int, object>().Call(L);
new AutoWrap.Func<object, int, int, int, int, object>().Call(L);
new AutoWrap.Func<object, int, int, int, int>().Call(L);
new AutoWrap.Func<object, int, int, int, object>().Call(L);
new AutoWrap.Func<object, int, int, int, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, int, int, int>().Call(L);
new AutoWrap.Func<object, int, int, object>().Call(L);
new AutoWrap.Func<object, int, int, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, int, int>().Call(L);
new AutoWrap.Func<object, int, long>().Call(L);
new AutoWrap.Func<object, int, object, float, int, int, int, int, bLua.AutoWrap.MultRet<bool, float>>().Call(L);
new AutoWrap.Func<object, int, object>().Call(L);
new AutoWrap.Func<object, int, System.IntPtr>().Call(L);
new AutoWrap.Func<object, int, uint>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.AnimatorStateInfo>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.AnimatorTransitionInfo>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Quaternion>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Rendering.ShaderTagId, UnityEngine.Rendering.ShaderTagId>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Rendering.SubMeshDescriptor>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Rendering.VertexAttributeDescriptor>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Vector2>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<object, int, UnityEngine.Vector4>().Call(L);
new AutoWrap.Func<object, int>().Call(L);
new AutoWrap.Func<object, long, long, long, object>().Call(L);
new AutoWrap.Func<object, long, long, object>().Call(L);
new AutoWrap.Func<object, long, object>().Call(L);
new AutoWrap.Func<object, long>().Call(L);
new AutoWrap.Func<object, object, bool, object, object>().Call(L);
new AutoWrap.Func<object, object, bool, object>().Call(L);
new AutoWrap.Func<object, object, bool>().Call(L);
new AutoWrap.Func<object, object, float, int, int, object>().Call(L);
new AutoWrap.Func<object, object, float, int, object>().Call(L);
new AutoWrap.Func<object, object, float, object>().Call(L);
new AutoWrap.Func<object, object, float>().Call(L);
new AutoWrap.Func<object, object, int, bool>().Call(L);
new AutoWrap.Func<object, object, int, int, bool, object>().Call(L);
new AutoWrap.Func<object, object, int, int, bool>().Call(L);
new AutoWrap.Func<object, object, int, int, int>().Call(L);
new AutoWrap.Func<object, object, int, int, object>().Call(L);
new AutoWrap.Func<object, object, int, int>().Call(L);
new AutoWrap.Func<object, object, int, object>().Call(L);
new AutoWrap.Func<object, object, int>().Call(L);
new AutoWrap.Func<object, object, object, object>().Call(L);
new AutoWrap.Func<object, object, object>().Call(L);
new AutoWrap.Func<object, object, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, object, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Func<object, object, UnityEngine.Vector2>().Call(L);
new AutoWrap.Func<object, object, UnityEngine.Vector4>().Call(L);
new AutoWrap.Func<object, object>().Call(L);
new AutoWrap.Func<object, System.IntPtr>().Call(L);
new AutoWrap.Func<object, uint>().Call(L);
new AutoWrap.Func<object, ulong>().Call(L);
new AutoWrap.Func<object, Unity.Collections.NativeArray<System.Byte>>().Call(L);
new AutoWrap.Func<object, Unity.Collections.NativeArray<UnityEngine.BoneWeight1>>().Call(L);
new AutoWrap.Func<object, UnityEngine.Bounds>().Call(L);
new AutoWrap.Func<object, UnityEngine.Color, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Color>().Call(L);
new AutoWrap.Func<object, UnityEngine.FrustumPlanes>().Call(L);
new AutoWrap.Func<object, UnityEngine.LightBakingOutput>().Call(L);
new AutoWrap.Func<object, UnityEngine.Matrix4x4, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.CollisionModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ColorBySpeedModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ColorOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.CustomDataModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.EmissionModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ExternalForcesModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ForceOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.InheritVelocityModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LifetimeByEmitterSpeedModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LightsModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.LimitVelocityOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.MainModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.NoiseModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.PlaybackState>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.RotationBySpeedModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.RotationOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.ShapeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SizeBySpeedModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SizeOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.SubEmittersModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TextureSheetAnimationModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TrailModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.Trails>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.TriggerModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.ParticleSystem.VelocityOverLifetimeModule>().Call(L);
new AutoWrap.Func<object, UnityEngine.Plane, UnityEngine.Plane>().Call(L);
new AutoWrap.Func<object, UnityEngine.Playables.PlayableGraph>().Call(L);
new AutoWrap.Func<object, UnityEngine.Quaternion, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Quaternion>().Call(L);
new AutoWrap.Func<object, UnityEngine.Rect>().Call(L);
new AutoWrap.Func<object, UnityEngine.RenderBuffer>().Call(L);
new AutoWrap.Func<object, UnityEngine.RenderTextureDescriptor>().Call(L);
new AutoWrap.Func<object, UnityEngine.SceneManagement.Scene>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector2, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector2>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, float, int, object>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, float, object>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, int, UnityEngine.Ray>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, int, UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, int>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, object>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Ray>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3, UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector4, bool>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector4, UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Func<object, UnityEngine.Vector4>().Call(L);
new AutoWrap.Func<object>().Call(L);
new AutoWrap.Func<ulong>().Call(L);
new AutoWrap.Func<UnityEngine.Color>().Call(L);
new AutoWrap.Func<UnityEngine.Matrix4x4>().Call(L);
new AutoWrap.Func<UnityEngine.PhysicsScene>().Call(L);
new AutoWrap.Func<UnityEngine.Quaternion>().Call(L);
new AutoWrap.Func<UnityEngine.Rect>().Call(L);
new AutoWrap.Func<UnityEngine.RenderBuffer>().Call(L);
new AutoWrap.Func<UnityEngine.Resolution>().Call(L);
new AutoWrap.Func<UnityEngine.Vector2>().Call(L);
new AutoWrap.Func<UnityEngine.Vector3>().Call(L);
new AutoWrap.Func<UnityEngine.Vector4>().Call(L);
}
}
}
